language: elixir
elixir:
  - 1.2.0
  - 1.3.0
otp_release:
  - 18.0
addons:
  postgresql: "9.4"
sudo: false # to use faster container based build environment
env:
  - ELIXIR_ERL_OPTIONS=""
  - ELIXIR_ERL_OPTIONS="+T 9"  # Find timing bugs: http://erlang.org/doc/man/erl.html#+T
script:
  - mix deps.get
  - MIX_ENV=test mix test.setup
  - mix test
